spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/xunwu?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      # 初始化大小 ，最大，最小
      initial-size: 10 #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      min-idle: 10     #最小连接池数量
      maxActive: 100   #最大连接池数量
      # 配置获取连接等待超时时间
      maxWait: 60000
      # 配置一个连接在池中的最小生存时间,单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      test-on-return: false
      # 打开 PSCache,并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall' 用于防火墙
      #      filters: stat,wall,log4j
      # 通过 connectProperties 属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.showSqlMillis=5000
      # 合并多个 DruidDataSource的监控数据
      # useGlobalDataSourceStat=true
      time-between-eviction-runs-millis: 60000
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    jedis:
      pool:
        min-idle: 1
  thymeleaf:
    cache: false
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 5MB
      enabled: true
      location: /tmp/xunwu/images/
  #  kafka:
  #    bootstrap-servers: localhost:9092
  #    consumer:
  #      group-id: xunwu
  #  data:
  #    elasticsearch:
  #      cluster-nodes: localhost:9300
  #      cluster-name: elasticsearch
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database: mysql
  session:
    store-type: redis
  mail:
    host: smtp.163.com
    username: flyzfq@163.com
    password: wali123
    properties:
      mail:
        smtp:
          auth=true: true
  main:
    allow-bean-definition-overriding: true
server:
  error:
    whitelabel:
      enabled: false
  port: 8087
qiniu:
  AccessKey: GVD-MVQEoOiJOt7yNBDo-JrOKWHB33eZN2JmDFC6
  SecretKey: sHnl57ZXtStejn7GgY5VF3lnm1CxMJ3hcayexAWz
  Bucket: lakers
  cdn:
    prefix: http://7xo6gy.com1.z0.glb.clouddn.com/
aliyun:
  sms:
    accessKey: LTAISjYxxr5qLmio
    accessKeySecret: pkqEMJIcVQV8G5fkNEQNDQV7rsntKV
    template:
      code: SMS_95590008
debug: true