# 配置文件加密
jasypt:
  encryptor:
    password: slmall

server:
  port: 5001

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

spring:
  application:
    name: slmall-portal
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/xmall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    # Jasyp加密 可到xcloud-common服务中找到JasyptUtil生成加密结果
    password: ENC(2iE6miNBKUKlZcFFp92geg==)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: ENC(2iE6miNBKUKlZcFFp92geg==)
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    # 自动生成表结构
    generate-ddl: false
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: true


  # Redis
  redis:
    host: 127.0.0.1
    password:
    # 数据库索引 默认0
    database: 0
    port: 6379
    timeout: 10000


# Swagger界面内容配置
swagger:
  title: sl-mall slmall-portal API接口文档
  description: sl-mall slmall-portal Api Documentation
  version: 1.0.0
  termsOfServiceUrl: https://github.com/CycloneBoy
  contact:
    name: cycloneboy
    url: https://github.com/CycloneBoy
    email: xuanfeng1992@gmail.com


# 关闭Spring Security
#security:
#  basic:
#    enabled: false


